import type {
  CaptaincyCentre,
  CommandCentre,
  DecisionCentre,
  MarketBoard,
  MarketSignal,
  ModelTrust,
  MultiGwPlanner,
  Player,
  PlayerComparison,
  PlannerRoute,
  PricingTier,
  ReviewAudit,
  SquadHealthDiagnostics,
  TransferRoute,
  UsageState,
  UserGameState,
  Watchlist,
} from "./types";

export const appState: UserGameState = {
  manager_name: "Manager",
  team_name: "Imported XI",
  team_id_label: "Connect team",
  gameweek: 1,
  gameweek_label: "GW1",
  deadline_label: "Next deadline 18:30",
  formation: "3-4-3",
  bank: 1.4,
  free_transfers: 1,
  current_tier: "Free",
};

export const usageState: UsageState = {
  current_tier: "Free",
  scenario_checks_used: 1,
  scenario_checks_limit: 3,
  market_signal_limit: 10,
  has_full_market: false,
  has_full_planner: false,
  has_transfer_comparisons: false,
  has_saved_plans: false,
  has_full_command_centre: false,
};

export const squadPlayers: Player[] = [
  { id: 1, api_id: 1, name: "Raya", team: "ARS", position: "GK", price: 5.6, projected: 4.2, fixture: "BOU (H)", fixture_difficulty: 2, ownership: 21.4, form: 4.6, three_gw_projected: 12.8, price_movement: 0.1, trend: "up", status: "Available", risk: "Low", role: "starter" },
  { id: 2, api_id: 5, name: "Gabriel", team: "ARS", position: "DEF", price: 6.1, projected: 5.4, fixture: "BOU (H)", fixture_difficulty: 2, ownership: 28.9, form: 5.1, three_gw_projected: 15.4, price_movement: 0.2, trend: "up", status: "Available", risk: "Low", role: "set-piece threat" },
  { id: 3, api_id: 568, name: "Porro", team: "TOT", position: "DEF", price: 5.8, projected: 4.8, fixture: "NEW (H)", fixture_difficulty: 3, ownership: 19.2, form: 4.4, three_gw_projected: 13.1, price_movement: 0, trend: "flat", status: "Available", risk: "Medium", role: "attacking full-back" },
  { id: 4, api_id: 476, name: "Burn", team: "NEW", position: "DEF", price: 4.6, projected: 3.6, fixture: "TOT (A)", fixture_difficulty: 4, ownership: 6.7, form: 2.9, three_gw_projected: 8.4, price_movement: -0.1, trend: "down", status: "Doubt", risk: "High", role: "minutes concern" },
  { id: 5, api_id: 235, name: "Palmer", team: "CHE", position: "MID", price: 10.8, projected: 7.1, fixture: "MCI (A)", fixture_difficulty: 5, ownership: 43.6, form: 7.2, three_gw_projected: 20.8, price_movement: 0.3, trend: "up", status: "Available", risk: "Low", role: "penalties" },
  { id: 6, api_id: 16, name: "Saka", team: "ARS", position: "MID", price: 10.2, projected: 6.7, fixture: "BOU (H)", fixture_difficulty: 2, ownership: 45.5, form: 6.8, three_gw_projected: 19.6, price_movement: 0.1, trend: "up", status: "Available", risk: "Low", role: "captain option" },
  { id: 7, api_id: 119, name: "Mbeumo", team: "BRE", position: "MID", price: 7.9, projected: 5.3, fixture: "LIV (A)", fixture_difficulty: 5, ownership: 15.8, form: 5.4, three_gw_projected: 14.2, price_movement: 0, trend: "flat", status: "Available", risk: "Medium", role: "fixtures turning" },
  { id: 8, api_id: 47, name: "Rogers", team: "AVL", position: "MID", price: 5.8, projected: 4.1, fixture: "NEW (H)", fixture_difficulty: 3, ownership: 18.1, form: 4.2, three_gw_projected: 11.9, price_movement: 0.1, trend: "up", status: "Available", risk: "Low", role: "value pick" },
  { id: 9, api_id: 430, name: "Haaland", team: "MCI", position: "FWD", price: 14.2, projected: 7.6, fixture: "CHE (H)", fixture_difficulty: 3, ownership: 63.2, form: 7.7, three_gw_projected: 22.3, price_movement: 0, trend: "flat", status: "Available", risk: "Low", role: "elite captain" },
  { id: 10, api_id: 499, name: "Isak", team: "NEW", position: "FWD", price: 9.5, projected: 6.0, fixture: "TOT (H)", fixture_difficulty: 3, ownership: 31.6, form: 6.1, three_gw_projected: 17.1, price_movement: 0.2, trend: "up", status: "Available", risk: "Medium", role: "upside forward" },
  { id: 11, api_id: 249, name: "Joao Pedro", team: "CHE", position: "FWD", price: 7.5, projected: 4.9, fixture: "MCI (A)", fixture_difficulty: 5, ownership: 12.4, form: 5.7, three_gw_projected: 14.6, price_movement: 0.4, trend: "up", status: "Available", risk: "Medium", role: "rotation watch" },
  { id: 12, api_id: 139, name: "Flekken", team: "BRE", position: "GK", price: 4.5, projected: 3.2, fixture: "LIV (A)", fixture_difficulty: 5, ownership: 7.8, form: 3.3, three_gw_projected: 8.8, price_movement: 0, trend: "flat", status: "Available", risk: "Medium", role: "bench keeper" },
  { id: 13, api_id: 260, name: "Guehi", team: "CRY", position: "DEF", price: 4.8, projected: 3.8, fixture: "ARS (A)", fixture_difficulty: 5, ownership: 9.4, form: 3.9, three_gw_projected: 11.2, price_movement: 0.1, trend: "up", status: "Available", risk: "Low", role: "safe minutes" },
  { id: 14, api_id: 517, name: "Anderson", team: "FUL", position: "MID", price: 4.5, projected: 2.1, fixture: "WHU (A)", fixture_difficulty: 3, ownership: 2.1, form: 2.5, three_gw_projected: 6.3, price_movement: 0, trend: "flat", status: "Available", risk: "Medium", role: "bench cover" },
  { id: 15, api_id: 338, name: "Muniz", team: "FUL", position: "FWD", price: 5.9, projected: 3.4, fixture: "WHU (A)", fixture_difficulty: 3, ownership: 6.1, form: 3.1, three_gw_projected: 9.5, price_movement: -0.1, trend: "down", status: "Doubt", risk: "High", role: "flagged bench" },
];

export const availablePlayers: Player[] = [
  ...squadPlayers,
  { id: 101, api_id: 414, name: "Foden", team: "MCI", position: "MID", price: 9.3, projected: 6.4, fixture: "CHE (H)", fixture_difficulty: 3, ownership: 22.7, form: 6.2, three_gw_projected: 18.5, price_movement: 0.2, trend: "up", status: "Available", risk: "Medium", role: "upside mid" },
  { id: 102, api_id: 64, name: "Watkins", team: "AVL", position: "FWD", price: 9.0, projected: 5.7, fixture: "NEW (H)", fixture_difficulty: 3, ownership: 27.8, form: 5.8, three_gw_projected: 16.7, price_movement: 0, trend: "flat", status: "Available", risk: "Low", role: "safe forward" },
  { id: 103, api_id: 266, name: "Eze", team: "CRY", position: "MID", price: 7.0, projected: 5.1, fixture: "ARS (A)", fixture_difficulty: 5, ownership: 13.2, form: 5.6, three_gw_projected: 15.8, price_movement: 0.3, trend: "up", status: "Available", risk: "Medium", role: "fixture swing" },
  { id: 104, api_id: 381, name: "Salah", team: "LIV", position: "MID", price: 12.8, projected: 7.3, fixture: "BRE (H)", fixture_difficulty: 2, ownership: 38.1, form: 7.4, three_gw_projected: 21.7, price_movement: 0.1, trend: "up", status: "Available", risk: "Low", role: "premium captain" },
  { id: 105, api_id: 624, name: "Bowen", team: "WHU", position: "MID", price: 7.8, projected: 4.7, fixture: "FUL (H)", fixture_difficulty: 3, ownership: 11.8, form: 4.1, three_gw_projected: 12.6, price_movement: -0.1, trend: "down", status: "Available", risk: "Medium", role: "hold only" },
  { id: 106, api_id: 596, name: "Solanke", team: "TOT", position: "FWD", price: 7.7, projected: 4.5, fixture: "NEW (A)", fixture_difficulty: 4, ownership: 18.9, form: 3.8, three_gw_projected: 12.2, price_movement: -0.2, trend: "down", status: "Available", risk: "Medium", role: "tough run" },
  { id: 107, api_id: 418, name: "Doku", team: "MCI", position: "MID", price: 6.6, projected: 4.6, fixture: "CHE (H)", fixture_difficulty: 3, ownership: 6.3, form: 4.9, three_gw_projected: 13.4, price_movement: 0.2, trend: "up", status: "Available", risk: "High", role: "minutes punt" },
];

export const transferRoutes: TransferRoute[] = [
  {
    id: "safe",
    title: "Best Safe Move",
    move: "Burn to Guehi",
    expected_gain: 4.4,
    confidence: "High",
    risk: "Low",
    route_type: "safe",
    why: ["Removes an availability concern", "Keeps money flexible", "Improves clean-sheet floor over the next three gameweeks"],
    why_this_could_be_wrong: ["A late team-news update could make Burn safer than expected"],
  },
  {
    id: "upside",
    title: "Highest Upside Move",
    move: "Mbeumo to Foden",
    expected_gain: 6.1,
    confidence: "Medium",
    risk: "Medium",
    route_type: "upside",
    why: ["Higher ceiling in the next two fixtures", "Better captaincy adjacency", "Strong attacking team context"],
    why_this_could_be_wrong: ["Minutes are less secure and the move uses more budget"],
  },
  {
    id: "roll",
    title: "Best Roll / No-Hit Move",
    move: "Roll transfer",
    expected_gain: 0,
    confidence: "High",
    risk: "Low",
    route_type: "roll",
    why: ["Squad can field a strong XI", "Two transfers next week creates better routes", "No urgent hit is required"],
    why_this_could_be_wrong: ["If Burn misses out, bench strength becomes thin"],
  },
];

export const marketSignals: MarketSignal[] = [
  { player: squadPlayers[5], signal: "Buy", score: 91, reason: "Premium projection with reliable minutes and strong fixtures." },
  { player: availablePlayers[15], signal: "Buy", score: 88, reason: "City upside with improving short-term fixtures." },
  { player: availablePlayers[18], signal: "Buy", score: 86, reason: "Premium captain profile and strong fixture entry point." },
  { player: squadPlayers[10], signal: "Watch", score: 72, reason: "Good price, but rotation risk keeps this from a clean buy." },
  { player: availablePlayers[17], signal: "Watch", score: 70, reason: "Underlying role is strong, but the immediate fixture is difficult." },
  { player: squadPlayers[3], signal: "Sell", score: 84, reason: "Availability and clean-sheet outlook both weaken the hold case." },
  { player: availablePlayers[20], signal: "Sell", score: 78, reason: "Price and fixture trend are moving against the hold case." },
  { player: squadPlayers[14], signal: "Avoid", score: 77, reason: "Risk is high enough that the upside does not compensate." },
  { player: availablePlayers[21], signal: "Avoid", score: 74, reason: "Minutes risk makes the upside hard to trust for now." },
  { player: squadPlayers[7], signal: "Hold", score: 69, reason: "Good value profile without enough urgency for a transfer." },
  { player: availablePlayers[19], signal: "Hold", score: 65, reason: "Useful fixture but not enough evidence to buy ahead of stronger options." },
  { player: squadPlayers[9], signal: "Hold", score: 81, reason: "Strong forward, but not the priority when squad structure needs attention." },
];

export const commandCentre: CommandCentre = {
  gameweek: appState.gameweek,
  deadline: appState.deadline_label,
  best_move: {
    recommended_action: "Transfer",
    move: "Burn to Guehi",
    expected_gain: 4.4,
    confidence_band: "High",
    risk_level: "Low",
    why: ["It fixes the weakest spot in the XI", "The replacement has better minutes security", "It keeps enough budget for next week"],
    why_this_could_be_wrong: ["If Burn is passed fit, the gain is smaller", "Clean-sheet swings are volatile"],
    fallback_used: false,
  },
  captain_pick: squadPlayers[8],
  vice_captain: squadPlayers[4],
  squad_health: {
    score: 78,
    grade: "Stable",
    minutes_risk: 22,
    injury_risk: 18,
    weak_bench_alerts: ["Bench cover is thin if Burn and Muniz both miss out."],
    captaincy_strength: "High",
  },
  transfer_preview: transferRoutes,
  planner: [
    { gw: "GW1", headline: "Fix defence", action: "Burn to Guehi", projected_points: 67.4, risk: "Low", captain: squadPlayers[8], fixture: "CHE (H)", fixture_difficulty: 3, warning: "Burn team-news flag remains the only urgent issue." },
    { gw: "GW2", headline: "Roll if team news holds", action: "Save transfer", projected_points: 64.1, risk: "Medium", captain: squadPlayers[4], fixture: "IPS (H)", fixture_difficulty: 2, warning: "Monitor Joao Pedro minutes before locking the bench." },
    { gw: "GW3", headline: "Upgrade midfield", action: "Review Mbeumo route", projected_points: 68.8, risk: "Medium", captain: squadPlayers[5], fixture: "MUN (A)", fixture_difficulty: 4, warning: "Midfield upside route depends on City minutes clarity." },
  ],
  market_alerts: marketSignals.slice(0, 5),
  risk_alerts: ["One defender has an availability flag", "Third bench slot is low impact", "Upside transfer route carries minutes risk"],
};

export const squadHealthDiagnostics: SquadHealthDiagnostics = {
  health: commandCentre.squad_health,
  urgent_issues: [
    { id: "burn-minutes", severity: "High", category: "Minutes", affected_player: squadPlayers[3], reason: "Availability flag plus difficult away fixture.", suggested_action: "Prioritise a safe defender replacement if no positive team news arrives." },
    { id: "muniz-flag", severity: "Medium", category: "Injury", affected_player: squadPlayers[14], reason: "Doubt status weakens bench cover.", suggested_action: "Do not take a hit, but avoid relying on him as first bench." },
  ],
  minutes_risk_list: [
    { id: "joao-minutes", severity: "Medium", category: "Minutes", affected_player: squadPlayers[10], reason: "Role is productive but rotation risk is still live.", suggested_action: "Start if the bench is stable; review if leaks suggest a rest." },
    { id: "doku-minutes", severity: "High", category: "Minutes", affected_player: availablePlayers[21], reason: "Upside comes with uncertain starts.", suggested_action: "Treat as a watchlist punt, not a safe transfer." },
  ],
  injury_suspension_risk_list: [
    { id: "burn-flag", severity: "High", category: "Injury", affected_player: squadPlayers[3], reason: "Flagged and projected below replacement level.", suggested_action: "Move to Guehi or another nailed defender." },
    { id: "muniz-doubt", severity: "Medium", category: "Injury", affected_player: squadPlayers[14], reason: "Bench player may not cover surprise absences.", suggested_action: "Keep only if two stronger bench options remain." },
  ],
  weak_bench_alerts: [
    { id: "bench-keeper", severity: "Medium", category: "Bench", affected_player: squadPlayers[11], reason: "Away fixture limits emergency cover.", suggested_action: "No transfer needed, but do not bench Raya for upside." },
    { id: "anderson-low-impact", severity: "Low", category: "Bench", affected_player: squadPlayers[13], reason: "Low projected ceiling from third bench slot.", suggested_action: "Accept for now unless rolling two transfers." },
  ],
  captaincy_strength: "High",
  fixture_problem_areas: [
    { id: "mbeumo-fixture", severity: "Medium", category: "Fixtures", affected_player: squadPlayers[6], reason: "Difficult immediate fixture lowers short-term ceiling.", suggested_action: "Hold unless moving to a clear upside route." },
    { id: "palmer-fixture", severity: "Low", category: "Fixtures", affected_player: squadPlayers[4], reason: "Tough fixture but role keeps him viable.", suggested_action: "Keep and use as vice-captain rather than captain." },
  ],
  transfer_pressure: {
    level: "Medium",
    reason: "One urgent defender issue, but the squad can still field a competitive XI without a hit.",
  },
  recommended_fix: {
    action: "Burn to Guehi",
    why: "It addresses the highest-severity issue without spending much bank or adding minutes risk.",
    confidence: "High",
    risk: "Low",
    why_this_could_be_wrong: "If Burn starts and keeps a clean sheet, the short-term edge narrows.",
  },
  players: squadPlayers,
};

export const captaincyCentre: CaptaincyCentre = {
  best_captain: {
    player: squadPlayers[8],
    projected_points: 7.6,
    ceiling: 14.8,
    safety: 84,
    minutes_risk: "Low",
    fixture_difficulty: 3,
    confidence: "High",
    risk: "Low",
    why: ["Highest raw projection", "Reliable minutes", "Central to the best attacking team context"],
    why_this_could_go_wrong: ["Chelsea fixture can be volatile", "A Saka home return could beat the safer projection"],
  },
  vice_captain: {
    player: squadPlayers[4],
    projected_points: 7.1,
    ceiling: 13.2,
    safety: 78,
    minutes_risk: "Low",
    fixture_difficulty: 5,
    confidence: "Medium",
    risk: "Medium",
    why: ["Penalty role protects floor", "Strong form", "Still viable even in a tough fixture"],
    why_this_could_go_wrong: ["Fixture difficulty caps team goal expectation"],
  },
  top_options: [],
  ceiling_vs_safety: "Haaland is the safest ceiling blend; Saka is the cleaner fixture play; Palmer is strong but fixture-capped.",
  minutes_risk_summary: "No captaincy candidate has a high minutes concern, but Joao Pedro is below the armband line.",
  fixture_difficulty_summary: "Saka has the best fixture, Haaland has the best projection, Palmer carries the hardest matchup.",
  why_this_captain: ["He leads the projection table", "He has the lowest minutes risk among premium options", "The vice choice still covers a penalty-heavy alternative"],
  what_could_go_wrong: ["A low-scoring City match narrows the edge", "Arsenal assets have a better fixture swing", "Late injury news could change the minutes model"],
};
captaincyCentre.top_options = [
  captaincyCentre.best_captain,
  captaincyCentre.vice_captain,
  {
    player: squadPlayers[5],
    projected_points: 6.7,
    ceiling: 12.6,
    safety: 81,
    minutes_risk: "Low",
    fixture_difficulty: 2,
    confidence: "High",
    risk: "Low",
    why: ["Best fixture among premium options", "Set-piece involvement", "Strong ownership shield"],
    why_this_could_go_wrong: ["Lower raw ceiling than Haaland"],
  },
  {
    player: squadPlayers[9],
    projected_points: 6.0,
    ceiling: 11.8,
    safety: 69,
    minutes_risk: "Medium",
    fixture_difficulty: 3,
    confidence: "Medium",
    risk: "Medium",
    why: ["Forward upside", "Home fixture", "Good form"],
    why_this_could_go_wrong: ["Team context is less reliable than the premium midfielders"],
  },
  {
    player: availablePlayers[18],
    projected_points: 7.3,
    ceiling: 14.1,
    safety: 80,
    minutes_risk: "Low",
    fixture_difficulty: 2,
    confidence: "High",
    risk: "Low",
    why: ["Elite projection", "Friendly fixture", "Strong penalty and bonus profile"],
    why_this_could_go_wrong: ["Not currently in the imported squad"],
  },
];

export const decisionCentre: DecisionCentre = {
  best_move: commandCentre.best_move,
  expected_gain: commandCentre.best_move.expected_gain,
  confidence: commandCentre.best_move.confidence_band,
  risk: commandCentre.best_move.risk_level,
  why_this_move: commandCentre.best_move.why,
  what_could_go_wrong: commandCentre.best_move.why_this_could_be_wrong,
  safe_alternative: transferRoutes[0],
  upside_alternative: transferRoutes[1],
  roll_alternative: transferRoutes[2],
  no_strong_move: false,
  buy_candidates: marketSignals.filter((signal) => signal.signal === "Buy").slice(0, 4),
  captain_pick: commandCentre.captain_pick,
  vice_captain_pick: commandCentre.vice_captain,
};

const recommendedPlannerRoute: PlannerRoute = {
  id: "balanced-three",
  title: "Recommended 3-GW Route",
  route_type: "safe",
  expected_total_points: 200.3,
  expected_gain: 10.8,
  confidence: "High",
  risk: "Low",
  steps: commandCentre.planner,
  warnings: ["Do not take a hit unless Burn is confirmed out", "Review midfield move after next deadline news"],
  why: ["Solves the urgent defender issue first", "Keeps enough bank for the midfield review", "Avoids paying for uncertain upside too early"],
  why_this_could_be_wrong: ["The upside midfield route may become obvious before GW2"],
};

export const multiGwPlanner: MultiGwPlanner = {
  status: "ok",
  horizon: 3,
  horizon_requested: 5,
  horizon_clamped: false,
  horizon_clamp_reason: null,
  current_gameweek: null,
  max_fixture_gameweek: null,
  fixture_calendar_available: true,
  fixture_calendar_stale: false,
  season_status: null,
  fixture_season: null,
  risk_profile: "Balanced",
  bank: appState.bank,
  free_transfers: appState.free_transfers,
  recommended_route: recommendedPlannerRoute,
  alternative_routes: [
    {
      id: "aggressive-three",
      title: "Aggressive 3-GW Route",
      route_type: "upside",
      expected_total_points: 203.7,
      expected_gain: 13.4,
      confidence: "Medium",
      risk: "Medium",
      steps: [
        { ...commandCentre.planner[0], headline: "Attack midfield", action: "Mbeumo to Foden", risk: "Medium", warning: "Minutes upside is real but volatile." },
        { ...commandCentre.planner[1], headline: "Patch defence", action: "Burn to Guehi if still flagged", risk: "Medium", warning: "Defender issue may force a lower-value move later." },
        { ...commandCentre.planner[2], headline: "Roll or rebalance", action: "Save transfer if Foden starts twice", risk: "Medium", warning: "Depends on City team news." },
      ],
      warnings: ["Higher ceiling, lower safety", "Bench cover becomes more important"],
      why: ["Maximises attacking upside", "Targets the highest expected route if minutes land"],
      why_this_could_be_wrong: ["One benching can erase the gain"],
    },
    {
      id: "roll-three",
      title: "Roll First Route",
      route_type: "roll",
      expected_total_points: 195.9,
      expected_gain: 6.4,
      confidence: "High",
      risk: "Low",
      steps: [
        { ...commandCentre.planner[0], headline: "Roll transfer", action: "Save transfer", risk: "Low", warning: "Only safe if Burn news improves." },
        { ...commandCentre.planner[1], headline: "Use two transfers", action: "Defence plus midfield review", risk: "Medium", warning: "Requires two clear targets." },
        { ...commandCentre.planner[2], headline: "Hold structure", action: "Avoid hit unless flags spread", risk: "Low", warning: "Lower ceiling than aggressive path." },
      ],
      warnings: ["Lower immediate expected points", "Best if late team news reduces the urgent issue"],
      why: ["Preserves flexibility", "Avoids a marginal transfer if team news improves"],
      why_this_could_be_wrong: ["A missed Burn start leaves points on the bench"],
    },
  ],
  locked_pro_preview: {
    id: "pro-five",
    title: "Locked 5-GW Pro Preview",
    route_type: "risk",
    expected_total_points: 332.6,
    expected_gain: 19.7,
    confidence: "Medium",
    risk: "Medium",
    steps: [
      ...commandCentre.planner,
      { gw: "GW4", headline: "Premium captain swing", action: "Review Salah route", projected_points: 66.9, risk: "Medium", captain: availablePlayers[18], fixture: "EVE (H)", fixture_difficulty: 2, warning: "Locked for Pro." },
      { gw: "GW5", headline: "Bench rebuild", action: "Upgrade third bench slot", projected_points: 65.4, risk: "Low", captain: squadPlayers[8], fixture: "WOL (H)", fixture_difficulty: 2, warning: "Locked for Pro." },
    ],
    warnings: ["Full five-gameweek planner is a Pro feature"],
    why: ["Longer horizon catches fixture swings earlier"],
    why_this_could_be_wrong: ["Long-range team news is less stable"],
  },
  usage: usageState,
};

export const marketBoard: MarketBoard = {
  rising_players: marketSignals.filter((signal) => signal.player.trend === "up").slice(0, 6),
  falling_players: marketSignals.filter((signal) => signal.player.trend === "down").slice(0, 5),
  owned_squad_alerts: marketSignals.filter((signal) => squadPlayers.some((player) => player.id === signal.player.id)),
  market_alerts: marketSignals,
  top_free_limit: usageState.market_signal_limit,
  full_market_locked: !usageState.has_full_market,
  signal_explanations: {
    Buy: "Projection, minutes, fixture, and price signals all point in the same direction.",
    Hold: "Useful player, but not enough transfer edge to spend a move.",
    Sell: "Risk, fixture, or value pressure is high enough to consider moving away.",
    Avoid: "Upside exists, but the downside is too large for the current price or role.",
    Watch: "Good signs, but wait for one more data point before buying.",
  },
};

export const playerComparison: PlayerComparison = {
  player_a: squadPlayers[6],
  player_b: availablePlayers[15],
  metrics: {
    projected_next_gw: [squadPlayers[6].projected, availablePlayers[15].projected],
    three_gw_projection: [squadPlayers[6].three_gw_projected ?? null, availablePlayers[15].three_gw_projected ?? null],
    fixture_difficulty: [squadPlayers[6].fixture_difficulty ?? 3, availablePlayers[15].fixture_difficulty ?? 3],
    minutes_risk: [squadPlayers[6].risk, availablePlayers[15].risk],
    ownership: [squadPlayers[6].ownership ?? 0, availablePlayers[15].ownership ?? 0],
    form: [squadPlayers[6].form ?? 0, availablePlayers[15].form ?? 0],
    stock_signal: ["Hold", "Buy"],
  },
  verdict: {
    winner: availablePlayers[15],
    summary: "Foden wins the upside case, but the confidence is not high enough to force it over the safe defender fix.",
    confidence: "Medium",
    risk: "Medium",
    why: ["Higher next-GW and 3-GW projection", "Better attacking team context", "Improves captaincy adjacency"],
    why_this_could_be_wrong: ["Minutes risk can undo the projection edge"],
  },
};

export const watchlist: Watchlist = {
  saved_players: [
    { player: availablePlayers[15], status: "Buy soon", reason: "Upside route opens if City team news improves.", trigger: "Start confirmed or price rise warning." },
    { player: availablePlayers[17], status: "Monitor", reason: "Strong role but poor immediate fixture.", trigger: "Fixture swing after the Arsenal match." },
    { player: availablePlayers[21], status: "Avoid", reason: "Minutes risk is too high for the current squad need.", trigger: "Two consecutive starts." },
    { player: squadPlayers[3], status: "Sell soon", reason: "Availability and fixture pressure are both moving the wrong way.", trigger: "No positive team-news update before deadline." },
  ],
  fixture_swing_alerts: ["Arsenal defensive run improves after the current deadline", "Palace midfielders move from avoid to monitor after the tough fixture"],
  price_value_alerts: ["Foden is close to a value signal if ownership keeps rising", "Muniz is trending down and should not block a better bench route"],
  empty_state: {
    title: "No saved players yet",
    body: "Use Market or Compare to save players as buy soon, monitor, or avoid.",
  },
};

export const reviewAudit: ReviewAudit = {
  last_gw_recommendation: "Roll transfer and captain Haaland",
  actual_outcome: "The roll preserved flexibility; captain returned near expectation.",
  result: "Good call",
  captain_result: "Haaland captain returned 14 points after armband doubling.",
  transfer_result: "No transfer avoided a low-value defender move before team news clarified.",
  model_note: "The model correctly valued flexibility higher than a marginal one-week defender switch.",
  lessons_for_next_gw: ["Do not chase a defender move without team-news edge", "Captaincy remains strong enough to avoid risky punts", "Bench depth is now the main pressure point"],
  confidence: "High",
  risk: "Low",
  what_could_go_wrong: ["A late injury can make a previously correct roll feel passive", "Clean-sheet variance can make defender calls noisy"],
};

export const modelTrust: ModelTrust = {
  prediction_system: "Recommendations are produced from model-backed player projections, fixture context, minutes estimates, and squad constraints.",
  confidence_risk_labels: "Every recommendation is labelled with confidence and risk so high-upside ideas do not look safer than they are.",
  fallback_warning: "If live data is incomplete, the UI warns you and uses safer fallback estimates instead of silent raw debug output.",
  previous_model_comparison: "The latest model comparison favoured the hybrid projection stack over the simpler baseline for ranking captaincy and transfer routes.",
  rollback_safety: "Rollback safety exists: the product can fall back to a stable prediction path if a newer model response is incomplete or inconsistent.",
};

export const pricingTiers: PricingTier[] = [
  {
    name: "Free",
    price: "\u00a30",
    summary: "Start with the core gameweek decision.",
    features: ["Best move each GW", "Squad Health", "Captain pick", "3 scenario checks", "Top 10 Market signals", "Basic 3-GW preview"],
  },
  {
    name: "Plus",
    price: "\u00a35",
    summary: "For managers who want every route compared.",
    highlight: true,
    features: ["Unlimited scenarios", "Full 3-GW Planner", "Full Player Market", "Transfer comparisons", "Saved plans", "Full Command Centre"],
  },
  {
    name: "Pro",
    price: "\u00a312",
    summary: "Advanced edge tools as the platform expands.",
    features: ["5-GW Planner later", "Differential finder later", "Mini-league chase later", "Advanced confidence/audit later", "Priority alerts later"],
  },
];
